version: '3'
services:
  tine20:
    image: tine20-server
    #build: .
    ports:
      - 80:80
    environment:
      - TINE20_DB_HOST=mariadb
      - TINE20_DB_USER=root
      - TINE20_DB_PASS=changeme
      - TINE20_SETUP_PASS=changeme2
    volumes:
      - files:/var/lib/tine20/files
      - config:/etc/tine20/

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=tine20
    volumes:
      - data:/var/lib/mysql

  redis:
    image: redis
    volumes:
      - cache:/data


volumes:
  config:
  data:
  files:
  cache:
